services:
  frontend:
    container_name: frontendcontainer
    build: .
    image: frontend:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - sensor-net

networks:
  sensor-net:
    external: true