services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    networks:
      - sensor-net

networks:
  sensor-net:
    external: true
